INSERT INTO house (id, building_age, area, city, floor, description, price, room_count, type) VALUES (1, 12, 912, 'Istanbul', 1, 'guzel is gorur', 2100, 10, 'arsa');
INSERT INTO house (id, building_age, area, city, floor, description, price, room_count, type) VALUES (2, 2, 412, 'Paris', 3, 'yani iste', 3100, 10, 'Ev');
INSERT INTO house (id, building_age, area, city, floor, description, price, room_count, type) VALUES (3, 5, 3212, 'Hong Kong', 92, 'gel gel', 5100, 10, 'Filla');
INSERT INTO house (id, building_age, area, city, floor, description, price, room_count, type) VALUES (4, 1, 2112, 'New York', 11, 'bu is olur', 2100, 10, 'Residence');
INSERT INTO house (id, building_age, area, city, floor, description, price, room_count, type) VALUES (5, 7, 1200, 'London', 22, 'hadi bakalim', 1100, 10, 'Gecekondu');
insert into image (id, url, house_id) VALUES (1, "lorempixel.com/g/800/600/", 1);
insert into image (id, url, house_id) VALUES (2, "lorempixel.com/g/800/600/", 1);
insert into image (id, url, house_id) VALUES (3, "lorempixel.com/g/800/600/", 1);
insert into image (id, url, house_id) VALUES (1, "lorempixel.com/g/800/600/", 2);
insert into image (id, url, house_id) VALUES (2, "lorempixel.com/g/800/600/", 2);
insert into image (id, url, house_id) VALUES (3, "lorempixel.com/g/800/600/", 2);
insert into image (id, url, house_id) VALUES (1, "lorempixel.com/g/800/600/", 3);
insert into image (id, url, house_id) VALUES (2, "lorempixel.com/g/800/600/", 3);
insert into image (id, url, house_id) VALUES (3, "lorempixel.com/g/800/600/", 4);
insert into image (id, url, house_id) VALUES (1, "lorempixel.com/g/800/600/", 4);
insert into image (id, url, house_id) VALUES (2, "lorempixel.com/g/800/600/", 5);
insert into image (id, url, house_id) VALUES (3, "lorempixel.com/g/800/600/", 4);